### ISSUE TITLE
idk coding i just wanna use the program for modding

### ISSUE THREAD

**Issue by Sonny4546** [jorgenpt/uasset-rs#1]
Hi sir, I wanna know how to use this program. The usage guide barely tells anything for me (I don't understand it) lol. Do I compile the program in rust to make it an exe file? Or is there an exe file already?

**Comment by jorgenpt** [comment]
Hello! This is a work-in-progress tool intended for use in development (verifying asset dependency graphs on check-in etc). What are you trying to use it for?

To answer your original question, it can either be used in your own Rust program that you write or it can be used as a standalone executable if you build it with `cargo build` from Rust.

**Comment by Sonny4546** [comment]
If possible I'm trying to use this for parsing a game uassets and view/read the data. If not then I maybe misunderstood this program for something else.

If i compile it to a gui program will there be commands for it or a GUI?

**Comment by jorgenpt** [comment]
It's probably not going to be what you need at the current time. It is a command line program, and it doesn't yet have support for looking into the internals of the game assets -- just the relationship between them.

**Comment by Sonny4546** [comment]
Ahh, I see I guess I did misunderstood it for something.

Okay thanks for the help!
